import './globals.css'
import logo from './assets/logo.png'
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>

      <title>7 Trials Strength Training</title>
      <link rel='icon' href={logo.src}/>


 
      <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'/>
      </head>
      <body>{children}</body>
    </html>
  )
}
